import 'dart:io';
import 'package:google_mlkit_face_mesh_detection/google_mlkit_face_mesh_detection.dart';
import 'package:tflite_flutter/tflite_flutter.dart';
import 'package:image/image.dart' as img;
import 'package:flutter/foundation.dart';

List<List<List<List<double>>>>? _prepareImageInput(Map<String, dynamic> params) {
  try {
    final imagePath = params['imagePath'] as String;
    final rectLeft = params['rectLeft'] as double;
    final rectTop = params['rectTop'] as double;
    final rectWidth = params['rectWidth'] as double;
    final rectHeight = params['rectHeight'] as double;

    final bytes = File(imagePath).readAsBytesSync();
    img.Image? capturedImage = img.decodeImage(bytes);
    if (capturedImage == null) return null;

    int marginX = (rectWidth * 0.1).toInt();
    int marginY = (rectHeight * 0.1).toInt();
    
    int x = (rectLeft.toInt() - marginX).clamp(0, capturedImage.width);
    int y = (rectTop.toInt() - marginY).clamp(0, capturedImage.height);
    int w = (rectWidth.toInt() + marginX * 2).clamp(0, capturedImage.width - x);
    int h = (rectHeight.toInt() + marginY * 2).clamp(0, capturedImage.height - y);
    
    img.Image faceCrop = img.copyCrop(capturedImage, x: x, y: y, width: w, height: h);
    img.Image resizedImage = img.copyResize(faceCrop, width: 224, height: 224);

    var input = List.generate(1, (i) => List.generate(224, (j) => List.generate(224, (k) => List.generate(3, (l) => 0.0))));
    
    for (int py = 0; py < 224; py++) {
      for (int px = 0; px < 224; px++) {
        final pixel = resizedImage.getPixel(px, py);
        input[0][py][px][0] = pixel.r / 255.0; // Red
        input[0][py][px][1] = pixel.g / 255.0; // Green
        input[0][py][px][2] = pixel.b / 255.0; // Blue
      }
    }
    return input;
  } catch (e) {
    debugPrint("Isolate Error: $e");
    return null;
  }
}

class FaceShapeResult {
  final String shape;
  final double confidence;

  FaceShapeResult(this.shape, this.confidence);
}

class TFLiteFaceDetector {
  Interpreter? _interpreter;
  
  // The exact labels generated by the Python script
  final List<String> _labels = ['Diamond', 'Heart', 'Oblong', 'Oval', 'Round', 'Square', 'Triangle'];
  
  Future<void> loadModel() async {
    try {
      _interpreter = await Interpreter.fromAsset('assets/models/face_shape_model.tflite');
    } catch (e) {
      debugPrint("Failed to load TFLite model: $e");
    }
  }

  Future<FaceShapeResult?> processImage(String imagePath, FaceMesh faceMesh) async {
    if (_interpreter == null) {
      debugPrint("TFLite Interpreter not loaded.");
      return null;
    }

    try {
      final input = await compute(_prepareImageInput, {
        'imagePath': imagePath,
        'rectLeft': faceMesh.boundingBox.left,
        'rectTop': faceMesh.boundingBox.top,
        'rectWidth': faceMesh.boundingBox.width,
        'rectHeight': faceMesh.boundingBox.height,
      });

      if (input == null) return null;

      // 5. Prepare the output tensor [1, 7] (for our 7 classes)
      var output = List.generate(1, (i) => List.filled(7, 0.0));

      // 6. Run the Neural Network!
      _interpreter!.run(input, output);
      final probabilities = output[0];
      
      // 7. Find the highest probability shape
      double maxProb = -1;
      int maxIndex = -1;
      
      for (int i = 0; i < probabilities.length; i++) {
        if (probabilities[i] > maxProb) {
          maxProb = probabilities[i];
          maxIndex = i;
        }
      }

      if (maxIndex != -1) {
        // Scale raw probability to a consumer-friendly percentage (80% - 99%)
        double displayConfidence = 0.80 + (maxProb.clamp(0.0, 1.0) * 0.19);
        return FaceShapeResult(_labels[maxIndex], displayConfidence);
      }
    } catch (e) {
      debugPrint("Error processing image with TFLite: $e");
    }

    return null;
  }
  
  void dispose() {
    _interpreter?.close();
  }
}
